<?php

namespace AppBundle\Repository;

/**
 * CreativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreativeRepository extends \Doctrine\ORM\EntityRepository
{
}
