<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Publisher;
use Doctrine\ORM\EntityRepository;

/**
 * CreativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreativeRepository extends EntityRepository
{
    public function createAlphabeticalQueryBuilder()
    {
        return $this->createQueryBuilder('creatives')
            ->orderBy('creatives.name', 'ASC');
    }
}
